# Generated by Django 5.2.3 on 2025-06-18 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('lgbtq', 'LGBTQ++'), ('na', 'N/A')], max_length=10)),
                ('status', models.CharField(choices=[('single', 'Single'), ('single_living_in', 'Single (Living in)'), ('married', 'Married'), ('separated', 'Separated'), ('widowed', 'Widowed'), ('na', 'N/A')], max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('source_of_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonForCalling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuicideMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Tawag Paglaum Code')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('6-2', '6am–2pm'), ('2-10', '2pm–10pm'), ('10-6', '10pm–6am'), ('8-4', '8am–4pm')], max_length=10)),
                ('time_called', models.TimeField()),
                ('time_ended', models.TimeField()),
                ('length_of_call', models.DurationField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_calling_for_others', models.BooleanField(default=False)),
                ('other_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other_person_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('other_person_status', models.CharField(blank=True, max_length=50, null=True)),
                ('other_person_age', models.PositiveIntegerField(blank=True, null=True)),
                ('other_person_location', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.caller')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interventions', models.ManyToManyField(blank=True, to='calls.intervention')),
                ('reasons_for_calling', models.ManyToManyField(blank=True, to='calls.reasonforcalling')),
                ('risk_details', models.ManyToManyField(blank=True, to='calls.riskdetail')),
                ('suicide_methods', models.ManyToManyField(blank=True, to='calls.suicidemethod')),
            ],
        ),
    ]
