# Generated by Django 5.2.3 on 2025-06-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOfInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='caller',
            name='source_of_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.sourceofinfo'),
        ),
    ]
