# Generated by Django 5.2.3 on 2025-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_populate_source_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='other_person_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('lgbtq', 'LGBTQ++'), ('na', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='other_person_status',
            field=models.CharField(choices=[('single', 'Single'), ('single_living_in', 'Single (Living in)'), ('married', 'Married'), ('separated', 'Separated'), ('widowed', 'Widowed'), ('na', 'N/A')], max_length=50),
        ),
    ]
