# Generated by Django 5.2.3 on 2025-06-19 07:42

import calls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_alter_callsession_other_person_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsession',
            name='interventions',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='reasons_for_calling',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='risk_details',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='suicide_methods',
        ),
        migrations.AddField(
            model_name='callsession',
            name='interventions',
            field=models.CharField(blank=True, verbose_name=calls.models.Intervention),
        ),
        migrations.AddField(
            model_name='callsession',
            name='reasons_for_calling',
            field=models.CharField(blank=True, verbose_name=calls.models.ReasonForCalling),
        ),
        migrations.AddField(
            model_name='callsession',
            name='risk_details',
            field=models.CharField(blank=True, verbose_name=calls.models.RiskDetail),
        ),
        migrations.AddField(
            model_name='callsession',
            name='suicide_methods',
            field=models.CharField(blank=True, verbose_name=calls.models.SuicideMethod),
        ),
    ]
