# Generated by Django 5.2.3 on 2025-06-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_remove_callsession_interventions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='interventions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.intervention'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='reasons_for_calling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.reasonforcalling'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='risk_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.riskdetail'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='suicide_methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.suicidemethod'),
        ),
    ]
