# Generated by Django 5.2.3 on 2025-06-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_alter_callsession_interventions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsession',
            name='code',
        ),
    ]
