# Generated by Django 5.2.3 on 2025-06-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_remove_callsession_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('designation', models.CharField(choices=[('Psychologist', 'Psychologist'), ('Psychiatrist', 'Psychiatrist')], default='Psychologist', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('alt_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
