# Generated by Django 5.2.3 on 2025-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_referralcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
