# Generated by Django 5.2.3 on 2025-06-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_referralcontact_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcontact',
            old_name='name',
            new_name='first_name',
        ),
    ]
