# Generated by Django 5.2.3 on 2025-06-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_alter_referralcontact_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcontact',
            name='designation',
            field=models.CharField(choices=[('Psychologist', 'Psychologist'), ('Psychiatrist', 'Psychiatrist')], max_length=20),
        ),
    ]
