# Generated by Django 5.2.3 on 2025-06-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0013_alter_referralcontact_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcontact',
            name='designation',
            field=models.CharField(choices=[('Psychologist', 'Psychologist'), ('Psychiatrist', 'Psychiatrist')], default='Psychologist', max_length=20),
        ),
        migrations.AlterField(
            model_name='referralcontact',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=10),
        ),
    ]
