# Generated by Django 5.2.3 on 2025-07-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0016_monthlyteleconsult'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='color',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
    ]
