# Generated by Django 5.2.3 on 2025-07-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0017_shifttype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyteleconsult',
            name='month',
            field=models.DateField(),
        ),
    ]
