# Generated by Django 5.2.3 on 2025-07-03 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0018_alter_monthlyteleconsult_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyteleconsult',
            unique_together={('responder', 'month')},
        ),
    ]
