# Generated by Django 5.2.3 on 2025-07-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0019_alter_monthlyteleconsult_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeoffrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.shifttype'),
        ),
    ]
